# These are supported funding model platforms

github: tonicpow
custom: https://tonicpow.com/?utm_source=github&utm_medium=sponsor-link&utm_campaign=go-moneybutton&utm_term=go-moneybutton&utm_content=go-moneybutton
